name = "allsoft-asia"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "VISITORS_DB"
database_name = "allsoft_visitors"
database_id = "5d2da4d8-2466-41be-816f-32e9c012e0e4"
